from enum import Enum


class NotificationType(str, Enum):
    # Claims
    CLAIM_SUBMITTED = "CLAIM_SUBMITTED"
    CLAIM_APPROVED = "CLAIM_APPROVED"
    CLAIM_REJECTED = "CLAIM_REJECTED"
    CLAIM_MORE_INFORMATION_REQUIRED = "CLAIM_MORE_INFORMATION_REQUIRED"
    CLAIM_STATUS_CHANGED = "CLAIM_STATUS_CHANGED"

    # Policies
    POLICY_CREATED = "POLICY_CREATED"
    POLICY_ASSIGNED = "POLICY_ASSIGNED"
    POLICY_RENEWAL = "POLICY_RENEWAL"
    POLICY_EXPIRED = "POLICY_EXPIRED"

    # Applications
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
    APPLICATION_APPROVED = "APPLICATION_APPROVED"
    APPLICATION_REJECTED = "APPLICATION_REJECTED"
    APPLICATION_MORE_INFORMATION_REQUIRED = "APPLICATION_MORE_INFORMATION_REQUIRED"

    # User / Admin
    USER_INVITED = "USER_INVITED"
    USER_ACTIVATED = "USER_ACTIVATED"
    ROLE_CHANGED = "ROLE_CHANGED"


class EntityType(str, Enum):
    CLAIM = "CLAIM"
    POLICY = "POLICY"
    APPLICATION = "APPLICATION"
    USER = "USER"
